<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Belajar Tajwid</title>
  </head>
  <body> 
    <ul>
    <?php foreach ($tajwids as $tajwid): ?>
      <li>
        <?php if (isset($tajwid['parent_id'])): ?>
	    <a href="?parent_id=<?php echo $tajwid['id'] ?>"><?php echo $tajwid['name']?></a>
        <?php else:?>
	    <audio id="sound_<?php echo $tajwid['id'] ?>" src="<?php echo $tajwid['recording_path'] ?>"></audio>
	    <a href="javascript:document.getElementById('sound_<?php echo $tajwid['id'] ?>').play()"><?php echo $tajwid['tajwid'] ?></a>
	<?php endif ?>
      </li>
    <?php endforeach ?>
    </ul>
  </body>
</html>
