<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Belajar Tajwid</title>
  </head>
  <body> 
    <ul>
    <?php foreach ($tajwids as $tajwid): ?>
      <li>
	<a href="<?php isset($tajwid['parent_id']) ? print '?parent_id=' . $tajwid['id'] : print '#' ?>"><?php (isset($tajwid['tajwid'])) ? print $tajwid['tajwid'] : print $tajwid['name'] ?></a>
      </li>
    <?php endforeach ?>
    </ul>
  </body>
</html>
